# Generated by Django 5.1.1 on 2024-11-28 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('PRICE', 'Price Target'), ('PERCENT_CHANGE', 'Percentage Change'), ('INDICATOR_CHAIN', 'Indicator Chain')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.stock')),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorChainAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_chain', to='alerts.alert')),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_line', models.CharField(blank=True, max_length=50, null=True)),
                ('indicator_timeframe', models.CharField(choices=[('1MIN', '1 Minute'), ('5MIN', '5 Minutes'), ('15MIN', '15 Minutes'), ('30MIN', '30 Minutes'), ('1H', '1 Hour'), ('4H', '4 Hours'), ('1D', '1 Day')], default='1H', max_length=10)),
                ('condition_operator', models.CharField(choices=[('GT', 'Greater Than'), ('LT', 'Less Than'), ('EQ', 'Equal To')], max_length=20)),
                ('value_type', models.CharField(choices=[('NUMBER', 'Number'), ('PRICE', 'Current Price'), ('INDICATOR_LINE', 'Indicator Line')], default='NUMBER', max_length=20)),
                ('value_number', models.FloatField(blank=True, null=True)),
                ('value_indicator_line', models.CharField(blank=True, max_length=50, null=True)),
                ('value_timeframe', models.CharField(blank=True, choices=[('1MIN', '1 Minute'), ('5MIN', '5 Minutes'), ('15MIN', '15 Minutes'), ('30MIN', '30 Minutes'), ('1H', '1 Hour'), ('4H', '4 Hours'), ('1D', '1 Day')], max_length=10, null=True)),
                ('indicator_parameters', models.JSONField(blank=True, null=True)),
                ('position_in_chain', models.PositiveIntegerField()),
                ('indicator_chain_alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='alerts.indicatorchainalert')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='alerts.indicatordefinition')),
                ('value_indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comparison_conditions', to='alerts.indicatordefinition')),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(default='Line', max_length=100)),
                ('indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='alerts.indicatordefinition')),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('lines', models.ManyToManyField(related_name='indicators', to='alerts.indicatorline')),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('param_type', models.CharField(choices=[('int', 'Integer'), ('float', 'Float'), ('string', 'String'), ('choice', 'Choice')], max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('default_value', models.CharField(blank=True, max_length=100, null=True)),
                ('choices', models.JSONField(blank=True, null=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='alerts.indicatordefinition')),
            ],
        ),
        migrations.CreateModel(
            name='PercentageChangeAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookback_period', models.CharField(blank=True, choices=[('1D', '1 Day'), ('1W', '1 Week'), ('1M', '1 Month'), ('1Y', '1 Year'), ('CUSTOM', 'Custom')], max_length=10, null=True)),
                ('custom_lookback_days', models.PositiveIntegerField(blank=True, null=True)),
                ('direction', models.CharField(choices=[('UP', 'Up'), ('DOWN', 'Down')], max_length=4)),
                ('percentage_change', models.DecimalField(decimal_places=2, max_digits=5)),
                ('check_interval', models.IntegerField(default=60)),
                ('alert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='percentage_change', to='alerts.alert')),
            ],
        ),
        migrations.CreateModel(
            name='PriceTargetAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_price', models.FloatField()),
                ('condition', models.CharField(blank=True, choices=[('GT', 'Greater Than'), ('LT', 'Less Than')], max_length=10, null=True)),
                ('check_interval', models.IntegerField(blank=True, null=True)),
                ('alert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_target_alert', to='alerts.alert')),
            ],
        ),
    ]
