# Generated by Django 5.1.1 on 2024-12-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorchainalert',
            name='check_interval',
            field=models.IntegerField(default=60),
        ),
    ]
