# Generated by Django 5.1.1 on 2024-12-20 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='indicatorchainalert',
            name='alert',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_chain', to='alerts.alert'),
        ),
        migrations.AddField(
            model_name='indicatorcondition',
            name='indicator_chain_alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='alerts.indicatorchainalert'),
        ),
        migrations.AddField(
            model_name='indicatorcondition',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='alerts.indicatordefinition'),
        ),
        migrations.AddField(
            model_name='indicatorcondition',
            name='value_indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comparison_conditions', to='alerts.indicatordefinition'),
        ),
        migrations.AddField(
            model_name='indicatorline',
            name='indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='alerts.indicatordefinition'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='lines',
            field=models.ManyToManyField(related_name='indicators', to='alerts.indicatorline'),
        ),
        migrations.AddField(
            model_name='indicatorparameter',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='alerts.indicatordefinition'),
        ),
        migrations.AddField(
            model_name='percentagechangealert',
            name='alert',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='percentage_change', to='alerts.alert'),
        ),
        migrations.AddField(
            model_name='pricetargetalert',
            name='alert',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_target_alert', to='alerts.alert'),
        ),
        migrations.AddField(
            model_name='alert',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.stock'),
        ),
    ]
