# Generated by Django 5.1.1 on 2025-01-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='percentagechangealert',
            name='custom_lookback_days',
        ),
        migrations.AlterField(
            model_name='percentagechangealert',
            name='lookback_period',
            field=models.CharField(blank=True, choices=[('5min', '5 Minutes'), ('15min', '15 Minutes'), ('30min', '30 Minutes'), ('1h', '1 Hour'), ('4h', '4 Hours'), ('1d', '1 Day'), ('1w', '1 Week'), ('2w', '2 Weeks'), ('1mo', '1 Month'), ('3mo', '3 Months')], max_length=10, null=True),
        ),
    ]
