# Generated by Django 5.1.1 on 2024-12-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_indicatorchainalert_check_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorcondition',
            name='value_indicator_parameters',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
