# Generated by Django 5.1.1 on 2025-01-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_remove_percentagechangealert_custom_lookback_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='asset_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='sector',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
