# Generated by Django 5.1.1 on 2024-10-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_indicatorline_remove_alert_stock_symbol_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='percentagechangealert',
            name='reference_price',
        ),
        migrations.AlterField(
            model_name='indicator',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
