# Generated by Django 5.1.1 on 2024-10-17 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_remove_percentagechangealert_reference_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='check_interval',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='pricetargetalert',
            name='condition',
            field=models.CharField(blank=True, choices=[('GT', 'Greater Than'), ('LT', 'Less Than')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pricetargetalert',
            name='alert',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_target_alert', to='alerts.alert'),
        ),
        migrations.AlterField(
            model_name='pricetargetalert',
            name='target_price',
            field=models.FloatField(),
        ),
    ]
