# Generated by Django 5.1.1 on 2025-01-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_stock_asset_type_stock_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='percentagechangealert',
            name='lookback_period',
            field=models.CharField(blank=True, choices=[('5MIN', '5 Minutes'), ('15MIN', '15 Minutes'), ('30MIN', '30 Minutes'), ('1H', '1 Hour'), ('4H', '4 Hours'), ('1D', '1 Day'), ('1W', '1 Week'), ('2W', '2 Weeks'), ('1MO', '1 Month'), ('3MO', '3 Months')], max_length=10, null=True),
        ),
    ]
