# Generated by Django 5.1.1 on 2024-10-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_alert_check_interval_pricetargetalert_condition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='check_interval',
        ),
        migrations.AddField(
            model_name='pricetargetalert',
            name='check_interval',
            field=models.IntegerField(default=60),
        ),
    ]
