# Generated by Django 5.1.1 on 2024-10-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_remove_alert_check_interval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricetargetalert',
            name='check_interval',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
