# Generated by Django 5.1.1 on 2024-10-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0007_alter_pricetargetalert_check_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='percentagechangealert',
            name='check_interval',
            field=models.IntegerField(default=60),
        ),
    ]
