# Generated by Django 5.1.1 on 2024-10-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0008_percentagechangealert_check_interval'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='indicatorcondition',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='indicatorcondition',
            name='indicator_timeframe',
            field=models.CharField(choices=[('1MIN', '1 Minute'), ('5MIN', '5 Minutes'), ('15MIN', '15 Minutes'), ('30MIN', '30 Minutes'), ('1H', '1 Hour'), ('4H', '4 Hours'), ('1D', '1 Day')], default='1H', max_length=10),
        ),
        migrations.AddField(
            model_name='indicatorcondition',
            name='value_indicator',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='indicatorcondition',
            name='value_indicator_line',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='indicatorcondition',
            name='value_number',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicatorcondition',
            name='value_timeframe',
            field=models.CharField(blank=True, choices=[('1MIN', '1 Minute'), ('5MIN', '5 Minutes'), ('15MIN', '15 Minutes'), ('30MIN', '30 Minutes'), ('1H', '1 Hour'), ('4H', '4 Hours'), ('1D', '1 Day')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='indicatorcondition',
            name='value_type',
            field=models.CharField(choices=[('NUMBER', 'Number'), ('PRICE', 'Current Price'), ('INDICATOR_LINE', 'Indicator Line')], default='NUMBER', max_length=20),
        ),
        migrations.AlterField(
            model_name='indicatorcondition',
            name='condition_operator',
            field=models.CharField(choices=[('CROSS_ABOVE', 'Crosses Above'), ('CROSS_BELOW', 'Crosses Below'), ('GT', 'Greater Than'), ('LT', 'Less Than'), ('EQ', 'Equal To')], max_length=20),
        ),
        migrations.AlterField(
            model_name='indicatorcondition',
            name='indicator',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='indicatorcondition',
            name='indicator_line',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='indicatorcondition',
            name='value',
        ),
    ]
