# Generated by Django 5.1.1 on 2024-10-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0009_alter_indicatorcondition_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorcondition',
            name='condition_operator',
            field=models.CharField(choices=[('GT', 'Greater Than'), ('LT', 'Less Than'), ('EQ', 'Equal To')], max_length=20),
        ),
    ]
