# Generated by Django 5.1.1 on 2024-11-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0010_alter_indicatorcondition_condition_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorcondition',
            name='indicator_parameters',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicatorcondition',
            name='lookback_period',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
