# Generated by Django 5.1.1 on 2025-01-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_phone_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='subscription_plan',
            field=models.CharField(choices=[('FREE', 'Free'), ('SILVER', 'Silver'), ('GOLD', 'Gold')], default='FREE', max_length=10),
        ),
    ]
