# Generated by Django 5.1.1 on 2025-01-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_subscription_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='subscription_plan',
            field=models.CharField(choices=[('tier0', 'Free'), ('tier1', 'Silver'), ('tier2', 'Gold')], default='tier0', max_length=10),
        ),
    ]
