# Generated by Django 5.1.1 on 2025-02-01 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_copy_subscription_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='old_subscription_plan',
        ),
    ]
