# Generated by Django 5.1.1 on 2025-02-01 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_customuser_old_subscription_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='new_subscription_plan',
            new_name='subscription_plan',
        ),
    ]
